### ISSUE TITLE
inspectors

### ISSUE THREAD

**Issue by jeanahelver** [RhubarbVR/RhubarbVR#28]
inspectors?

**Comment by Reiko9** [comment]
Brilliant!  
I visualize this Snapping functionality driven by selecting a Window, then Clicking the Edge of another window, where you want the Top Edge of the grabbed window to Align. (Square Corner-Points could indicate a perfectly flush snapping point)

┏━━━━━━━┓                                  ┏━━━━━━━┓  (selected)  
┃ window ┃                                  ┃ window ┃
┃              ┃<==click here             ┃              ┃
┃      A      ┃                                  ┃      B     ┃
┃              ┃                                  ┃              ┃
┗━━━━━━━┛                                  ┗━━━━━━━┛

Results:
┏━━━━━━━┓               
┃ window ┃
┃              ┃┏━━━━━━━┓
┃      A      ┃┃ window ┃
┃              ┃┃              ┃
┗━━━━━━━┛┃      A      ┃
                  ┃              ┃
                  ┗━━━━━━━┛

(The Windows could be Scaled by grabbing onto any of the 4 Corners and Click dragging, if the content layout is simple enough, then it could Scale to the Window-size automatically)

Windows touching each other can have their borders corner dots join and click dragging effects are applied to all windows connected to the corner square being click dragged.

▇━━━━━━━▇━━━━━━━▇               
┃ window  ┃ window  ┃
┃               ┃              ┃
┃      A       ┃      B      ┃
┃               ┃              ┃
▇━━━━━━━▇━━━━━━━▇
                 ^        
                 |
       (drag up center would result in below results)


▇━━━━━━━▇━━━━━━━▇               
┃ window  ┃ window  ┃
┃      A       ┃      B      ┃
▇━━━━━━━▇━━━━━━━▇

Granted it seems like an obvious toggle option to Join/un-join window tile corners, because in some cases it makes things easier and in some others it may be a limitation.

Obviously Dragging up a non-joined edge would have a result somewhat like this:

▇━━━━━━━▇━━━━━━━▇               
┃ window  ┃ window  ┃
┃               ┃              ┃
┃      A       ┃      B      ┃
┃               ┃              ┃
▇━━━━━━━▇━━━━━━━▇
                                 ^        
                                 |
             (drag up right corner would result in below results)


▇━━━━━━━▇━━━━━━━▇               
┃ window  ┃ window  ┃
┃               ┃      B      ┃
┃      A       ▇━━━━━━ ▇
┃               ┃              
▇━━━━━━━▇


(So Obviously hiding edges and corners is something folks would frequently do to save screen space)

This ASC2 art uses Box-drawing characters and it needs viewed on large enough of a screen (preferably a laptop or desktop)

**Comment by Faolan-Rad** [comment]
Rhubarbs form of inspectors is in this release
https://github.com/RhubarbVR/RhubarbVR/releases/tag/v0.0.0.8.1-PrePreAlpha
